name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        
        script: |

          cd /var/www/html/

          git checkout -f 

          git pull origin master

